apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.126.com:25'
      smtp_from: 'XXXXXX@126.com'
      smtp_auth_username: 'XXXXXXX@126.com'
      smtp_auth_password: 'XXXXXXXXXXX'
      smtp_hello: '126.com'
      smtp_require_tls: false
    inhibit_rules:
    - equal:
      - namespace
      - alertname
      source_match:
        severity: critical
      target_match_re:
        severity: warning|info
    - equal:
      - namespace
      - alertname
      source_match:
        severity: warning
      target_match_re:
        severity: info
    route:
      group_by:
      - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: webhook
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: webhook
      - match:
          severity: critical
        receiver: webhook
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: 'http://dingtalk-hook.kube-ops.svc.cluster.local:5000'
    - name: 'default'
      email_configs:
      - to: 'XXXXXXXX@qq.com'
        send_resolved: true
type: Opaque
