apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingtalk-hook
  labels:
    app: dingtalk-hook
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dingtalk-hook
        octopusexport: OctopusExport
    spec:
      containers:
        - name: dingtalk-hook
          image: 'yangpeng2468/alertmanager-dingtalk-hook:v1'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: ROBOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dingtalk-secret
                  key: token
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 50m
